#!/bin/sh
# live-build configuration for Edemint
# This script is invoked by `lb config` and defines how the image is assembled.

set -e

lb config noauto \
	--mode debian \
	--distribution trixie \
	--archive-areas "main contrib non-free non-free-firmware" \
	--architectures amd64 \
	--linux-flavours amd64 \
	--binary-images iso-hybrid \
	--debian-installer none \
	--security false \
	--bootappend-live "boot=live components quiet splash hostname=edemint username=edemint mitigations=auto,nosmt amd_pstate=guided intel_pstate=active pcie_aspm=force nowatchdog" \
	--memtest none \
	--win32-loader false \
	--apt-recommends false \
	--firmware-chroot false \
	--firmware-binary false \
	--initsystem systemd \
	--iso-application "Edemint" \
	--iso-volume "Edemint Live" \
	--iso-preparer "edemint" \
	--iso-publisher "edemint" \
	"${@}"
