---
# Edemint partition defaults — btrfs root pairs with snapper/grub-btrfs (§0g).
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512MiB
userSwapChoices:
    - none
    - file
defaultFileSystemType:  btrfs
availableFileSystemTypes:  ["btrfs", "ext4", "f2fs", "xfs"]
enableLuksAutomatedPartitioning: true
allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice: file
